### ISSUE TITLE
Visual Studio Development Servers removed in VS2013

### ISSUE THREAD

**Issue by blowsie** [jocull/SharpProxy#1]
With Visual Studio Development Servers being removed in VS2013 is there any plans to make this work with IIS express?

**Comment by jocull** [comment]
I live in the past (VS 2010 day-to-day still!) and haven't used IIS express, but it was my understanding that you can host to external addresses with it. If that's true then you don't need to proxy anything at all. Can you confirm?

**Comment by blowsie** [comment]
I've tried following various instructions on the web to access my dev server over wifi but I cant get anything to work. SharpProxy simply just works a charm for me up to VS2012

**Comment by jocull** [comment]
I bet there is a simple host-header or site binding issue with IIS Express... I will try to look into it sometime.

**Comment by jocull** [comment]
I added new options today that support IIS Express host headers. They will be rewritten to `localhost:port` for any incoming requests. Enjoy!

**Comment by blowsie** [comment]
Excellent, Thank you !
